{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "guardrail-ai.fullname" . }}
  labels:
    {{- include "guardrail-ai.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- if .Values.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "guardrail-ai.fullname" . }}-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "guardrail-ai.fullname" . }}-frontend
                port:
                  name: http
{{- end }}
