apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardrail-ai.fullname" . }}-secrets
  labels:
    {{- include "guardrail-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.config.secretKey | quote }}
  encryption-key: {{ .Values.config.encryptionKey | quote }}
  database-url: {{ .Values.config.databaseUrl | quote }}
  neo4j-password: {{ .Values.config.neo4jPassword | quote }}
